### ISSUE TITLE
cannot import name 'Qwen2_5_VLForConditionalGeneration' from 'transformers'

### ISSUE THREAD

**Issue by gtbloody** [IuvenisSapiens/ComfyUI_Qwen2-VL-Instruct#30]
pytorch version: 2.5.1+cu124
cuda:12.4
xformers version: 0.0.28.post3
python :3.11

**Comment by gtbloody** [comment]
![Image](https://github.com/user-attachments/assets/96aae617-35b8-45f1-ba3e-5163ee12061a) nodes import failed

**Comment by gtbloody** [comment]
fixed after upgrade transformers to 4.49
